export const teamNames = [
	// EPL
	{ id: 42, nameLong: { ua: 'Арсенал', en: 'Arsenal' }, nameShort: { ua: 'АРС', en: 'ARS' } },
	{ id: 40, nameLong: { ua: 'Ліверпуль', en: 'Liverpool' }, nameShort: { ua: 'ЛІВ', en: 'LIV' } },
	{ id: 66, nameLong: { ua: 'Астон Вілла', en: 'Aston Villa' }, nameShort: { ua: 'АВІ', en: 'AVI' } },
	{ id: 50, nameLong: { ua: 'Манчестер Сіті', en: 'Manchester City' }, nameShort: { ua: 'МС', en: 'MCI' } },
	{ id: 47, nameLong: { ua: 'Тоттенхем', en: 'Tottenham' }, nameShort: { ua: 'ТОТ', en: 'TOT' } },
	{ id: 34, nameLong: { ua: 'Ньюкасл', en: 'Newcastle' }, nameShort: { ua: 'НЮК', en: 'NEW' } },
	{ id: 33, nameLong: { ua: 'Манчестер Юнайтед', en: 'Manchester United' }, nameShort: { ua: 'МЮ', en: 'MUN' } },
	{ id: 48, nameLong: { ua: 'Вест Хем', en: 'West Ham United' }, nameShort: { ua: 'ВХ', en: 'WHA' } },
	{ id: 51, nameLong: { ua: 'Брайтон', en: 'Brighton' }, nameShort: { ua: 'БРА', en: 'BRI' } },
	{ id: 49, nameLong: { ua: 'Челсі', en: 'Chelsea' }, nameShort: { ua: 'ЧЕЛ', en: 'CHE' } },
	{ id: 36, nameLong: { ua: 'Фулхем', en: 'Fulham' }, nameShort: { ua: 'ФУЛ', en: 'FUL' } },
	{ id: 55, nameLong: { ua: 'Брентфорд', en: 'Brentfort' }, nameShort: { ua: 'БРЕ', en: 'BRE' } },
	{ id: 39, nameLong: { ua: 'Вулвергемптон', en: 'Wolverhampton' }, nameShort: { ua: 'ВУЛ', en: 'WOL' } },
	{ id: 35, nameLong: { ua: 'Борнмут', en: 'Bournemouth' }, nameShort: { ua: 'БОР', en: 'BOR' } },
	{ id: 52, nameLong: { ua: 'Крістал Пелас', en: 'Crystal Palace' }, nameShort: { ua: 'КРІ', en: 'CRY' } },
	{ id: 45, nameLong: { ua: 'Евертон', en: 'Everton' }, nameShort: { ua: 'ЕВЕ', en: 'EVE' } },
	{ id: 65, nameLong: { ua: 'Ноттінгем Форест', en: 'Nottingham Forest' }, nameShort: { ua: 'НОТ', en: 'NOT' } },
	{ id: 1359, nameLong: { ua: 'Лутон', en: 'Luton' }, nameShort: { ua: 'ЛУТ', en: 'LUT' } },
	{ id: 44, nameLong: { ua: 'Бернлі', en: 'Burnley' }, nameShort: { ua: 'БЕР', en: 'BUR' } },
	{ id: 62, nameLong: { ua: 'Шеффілд Юнайтед', en: 'Sheffield United' }, nameShort: { ua: 'ШЕФ', en: 'sHE' } },

	// LALIGA
	{ id: 541, nameLong: { ua: 'Реал Мадрид', en: 'Real Madrid' }, nameShort: { ua: 'РЕА', en: 'RMA' } },
	{ id: 547, nameLong: { ua: 'Жирона', en: 'Girona' }, nameShort: { ua: 'ЖИР', en: 'GIR' } },
	{ id: 529, nameLong: { ua: 'Барселона', en: 'Barcelona' }, nameShort: { ua: 'БАР', en: 'BAR' } },
	{ id: 530, nameLong: { ua: 'Атлетіко Мадрид', en: 'Atletico Madrid' }, nameShort: { ua: 'АТМ', en: 'ATM' } },
	{ id: 531, nameLong: { ua: 'Атлетік Більбао', en: 'Athletic Bilbao' }, nameShort: { ua: 'АТЛ', en: 'ATB' } },
	{ id: 548, nameLong: { ua: 'Реал Сосьєдад', en: 'Real Sociedad' }, nameShort: { ua: 'СОС', en: 'RSO' } },
	{ id: 543, nameLong: { ua: 'Реал Бетіс', en: 'Real Betis' }, nameShort: { ua: 'БЕТ', en: 'BET' } },
	{ id: 546, nameLong: { ua: 'Хетафе', en: 'Getafe' }, nameShort: { ua: 'ХЕТ', en: 'GET' } },
	{ id: 534, nameLong: { ua: 'Лас Пальмас', en: 'Las Palmas' }, nameShort: { ua: 'ЛАС', en: 'LAS' } },
	{ id: 532, nameLong: { ua: 'Валенсія', en: 'Valencia' }, nameShort: { ua: 'ВАЛ', en: 'VAL' } },
	{ id: 728, nameLong: { ua: 'Райо Вальєкано', en: 'Rayo Vallecano' }, nameShort: { ua: 'РАЙ', en: 'RAY' } },
	{ id: 727, nameLong: { ua: 'Осасуна', en: 'Osasuna' }, nameShort: { ua: 'ОСА', en: 'OSA' } },
	{ id: 533, nameLong: { ua: 'Вільяреал', en: 'Villarreal' }, nameShort: { ua: 'ВІЛ', en: 'VIL' } },
	{ id: 798, nameLong: { ua: 'Мальорка', en: 'Mallorca' }, nameShort: { ua: 'МАЛ', en: 'MAL' } },
	{ id: 536, nameLong: { ua: 'Севілья', en: 'Sevilla' }, nameShort: { ua: 'СЕВ', en: 'SEV' } },
	{ id: 542, nameLong: { ua: 'Алавес', en: 'Alaves' }, nameShort: { ua: 'АЛА', en: 'ALA' } },
	{ id: 724, nameLong: { ua: 'Кадіз', en: 'Cadiz' }, nameShort: { ua: 'КАД', en: 'CAD' } },
	{ id: 538, nameLong: { ua: 'Сельта', en: 'Celta Vigo' }, nameShort: { ua: 'СЕЛ', en: 'CEL' } },
	{ id: 715, nameLong: { ua: 'Гранада', en: 'Granada' }, nameShort: { ua: 'ГРА', en: 'GRA' } },
	{ id: 723, nameLong: { ua: 'Альмерія', en: 'Almeria' }, nameShort: { ua: 'АЛМ', en: 'ALM' } },

	// Serie A
	{ id: 505, nameLong: { ua: 'Інтер', en: 'Inter' }, nameShort: { ua: 'ІНТ', en: 'INT' } },
	{ id: 496, nameLong: { ua: 'Ювентус', en: 'Juventus' }, nameShort: { ua: 'ЮВЕ', en: 'JUV' } },
	{ id: 489, nameLong: { ua: 'Мілан', en: 'AC Milan' }, nameShort: { ua: 'МІЛ', en: 'MIL' } },
	{ id: 502, nameLong: { ua: 'Фіорентина', en: 'Fiorentina' }, nameShort: { ua: 'ФІО', en: 'FIO' } },
	{ id: 500, nameLong: { ua: 'Болонья', en: 'Bologna' }, nameShort: { ua: 'БОЛ', en: 'BOL' } },
	{ id: 492, nameLong: { ua: 'Наполі', en: 'Napoli' }, nameShort: { ua: 'НАП', en: 'NAP' } },
	{ id: 499, nameLong: { ua: 'Аталанта', en: 'Atalanta' }, nameShort: { ua: 'АТА', en: 'ATA' } },
	{ id: 497, nameLong: { ua: 'Рома', en: 'AS Roma' }, nameShort: { ua: 'РОМ', en: 'ROM' } },
	{ id: 487, nameLong: { ua: 'Лаціо', en: 'Lazio' }, nameShort: { ua: 'ЛАЦ', en: 'LAZ' } },
	{ id: 503, nameLong: { ua: 'Торіно', en: 'Torino' }, nameShort: { ua: 'ТОР', en: 'TOR' } },
	{ id: 1579, nameLong: { ua: 'Монца', en: 'Monza' }, nameShort: { ua: 'МОН', en: 'MON' } },
	{ id: 867, nameLong: { ua: 'Лечче', en: 'Lecce' }, nameShort: { ua: 'ЛЕЧ', en: 'LEC' } },
	{ id: 495, nameLong: { ua: 'Дженоа', en: 'Genoa' }, nameShort: { ua: 'ДЖЕ', en: 'GEN' } },
	{ id: 512, nameLong: { ua: 'Фрозіноне', en: 'Frozinone' }, nameShort: { ua: 'ФРО', en: 'FRO' } },
	{ id: 488, nameLong: { ua: 'Сасуоло', en: 'Sassuolo' }, nameShort: { ua: 'САС', en: 'SAS' } },
	{ id: 490, nameLong: { ua: 'Кальярі', en: 'Cagliari' }, nameShort: { ua: 'КЛР', en: 'CAG' } },
	{ id: 494, nameLong: { ua: 'Удінезе', en: 'Udinese' }, nameShort: { ua: 'УДІ', en: 'UDI' } },
	{ id: 511, nameLong: { ua: 'Емполі', en: 'Empoli' }, nameShort: { ua: 'ЕМП', en: 'EMP' } },
	{ id: 504, nameLong: { ua: 'Верона', en: 'Verona' }, nameShort: { ua: 'ВЕР', en: 'VER' } },
	{ id: 514, nameLong: { ua: 'Салернітана', en: 'Salernitana' }, nameShort: { ua: 'САЛ', en: 'SAL' } },

	// Bundesliga
	{ id: 168, nameLong: { ua: 'Байєр Леверкузен', en: 'Bayer Leverkusen' }, nameShort: { ua: 'БАЙ', en: 'BAY' } },
	{ id: 157, nameLong: { ua: 'Баварія Мюнхен', en: 'Bayern Munich' }, nameShort: { ua: 'БАВ', en: 'BRN' } },
	{ id: 172, nameLong: { ua: 'Штудгарт', en: 'VfB Stuttgart' }, nameShort: { ua: 'ШТУ', en: 'STU' } },
	{ id: 173, nameLong: { ua: 'Лейпціг', en: 'RB Leipzig' }, nameShort: { ua: 'ЛЕЙ', en: 'LEI' } },
	{ id: 165, nameLong: { ua: 'Боруссія Дортмунд', en: 'Borussia Dortmund' }, nameShort: { ua: 'ДОР', en: 'DOR' } },
	{ id: 169, nameLong: { ua: 'Айнтрахт', en: 'Eintracht' }, nameShort: { ua: 'АЙН', en: 'EIN' } },
	{ id: 167, nameLong: { ua: 'Хоффенхайм', en: '1899 Hoffenheim' }, nameShort: { ua: 'ХОФ', en: 'HOF' } },
	{ id: 160, nameLong: { ua: 'Фрайбург', en: 'SC Freiburg' }, nameShort: { ua: 'ФРА', en: 'FRE' } },
	{ id: 180, nameLong: { ua: 'Гайденгайм', en: 'FC Heidenheim' }, nameShort: { ua: 'ГАЙ', en: 'HEI' } },
	{ id: 161, nameLong: { ua: 'Вольфсбург', en: 'VfL Wolfsburg' }, nameShort: { ua: 'ВОЛ', en: 'WOL' } },
	{ id: 170, nameLong: { ua: 'Аугсбург', en: 'FC Augsburg' }, nameShort: { ua: 'АУГ', en: 'AUG' } },
	{ id: 163, nameLong: { ua: 'Боруссія М', en: 'Borussia M' }, nameShort: { ua: 'МЕН', en: 'MON' } },
	{ id: 162, nameLong: { ua: 'Вердер Бремен', en: 'Werder Bremen' }, nameShort: { ua: 'ВЕР', en: 'BRE' } },
	{ id: 176, nameLong: { ua: 'Бохум', en: 'Vfl Bochum' }, nameShort: { ua: 'БОХ', en: 'BOC' } },
	{ id: 182, nameLong: { ua: 'Уніон Берлін', en: 'Union Berlin' }, nameShort: { ua: 'УНІ', en: 'UNI' } },
	{ id: 164, nameLong: { ua: 'Майнц', en: 'FSV Mainz 05' }, nameShort: { ua: 'МАЙ', en: 'M05' } },
	{ id: 192, nameLong: { ua: 'Кьольн', en: 'FC Köln' }, nameShort: { ua: 'КЛН', en: 'KOL' } },
	{ id: 181, nameLong: { ua: 'Дармштандт', en: 'SV Darmstadt 98' }, nameShort: { ua: 'ДАР', en: 'DAR' } },

	// Ligue 1
	{ id: 85, nameLong: { ua: 'ПСЖ', en: 'Paris Saint Germain' }, nameShort: { ua: 'ПСЖ', en: 'PSG' } },
	{ id: 84, nameLong: { ua: 'Ніцца', en: 'Nice' }, nameShort: { ua: 'НАЦ', en: 'NIC' } },
	{ id: 91, nameLong: { ua: 'Монако', en: 'Monaco' }, nameShort: { ua: 'МОН', en: 'MON' } },
	{ id: 106, nameLong: { ua: 'Брест', en: 'Stade Brestois 29' }, nameShort: { ua: 'БРЕ', en: 'BRE' } },
	{ id: 79, nameLong: { ua: 'Лілль', en: 'Lille' }, nameShort: { ua: 'ЛЛЬ', en: 'LIL' } },
	{ id: 81, nameLong: { ua: 'Марсель', en: 'Marseille' }, nameShort: { ua: 'МАР', en: 'MAR' } },
	{ id: 116, nameLong: { ua: 'Ланс', en: 'Lens' }, nameShort: { ua: 'ЛАН', en: 'LEN' } },
	{ id: 93, nameLong: { ua: 'Реймс', en: 'Reims' }, nameShort: { ua: 'РЕЙ', en: 'REI' } },
	{ id: 95, nameLong: { ua: 'Стратсбург', en: 'Strasbourg' }, nameShort: { ua: 'СТР', en: 'STR' } },
	{ id: 94, nameLong: { ua: 'Ренн', en: 'Rennes' }, nameShort: { ua: 'РЕН', en: 'REN' } },
	{ id: 111, nameLong: { ua: 'Гавр', en: 'LE Havre' }, nameShort: { ua: 'ГАВ', en: 'HAV' } },
	{ id: 82, nameLong: { ua: 'Монпельє', en: 'Montpellier' }, nameShort: { ua: 'МПЛ', en: 'MPL' } },
	{ id: 83, nameLong: { ua: 'Нант', en: 'Nantes' }, nameShort: { ua: 'НАН', en: 'NAN' } },
	{ id: 112, nameLong: { ua: 'Метз', en: 'Metz' }, nameShort: { ua: 'МЕТ', en: 'MET' } },
	{ id: 80, nameLong: { ua: 'Ліон', en: 'Lyon' }, nameShort: { ua: 'ЛІО', en: 'LYO' } },
	{ id: 96, nameLong: { ua: 'Тулуза', en: 'Toulouse' }, nameShort: { ua: 'ТУЛ', en: 'TOU' } },
	{ id: 97, nameLong: { ua: 'Лорьян', en: 'Lorient' }, nameShort: { ua: 'ЛОР', en: 'LOR' } },
	{ id: 99, nameLong: { ua: 'Клермон', en: 'Clermont Foot' }, nameShort: { ua: 'КЛЕ', en: 'CLE' } }
]

// export const teamNames = []
